### ISSUE TITLE
Content not clickable

### ISSUE THREAD

**Issue by jackmcdade** [euvl/vue-js-dropdown#2]
If I put a link inside the dropdown, I can't click it.

**Comment by euvl** [comment]
Hey @jackmcdade , try v1.0.2, should work. Ty

**Comment by jackmcdade** [comment]
Still no luck, sorry!

**Comment by jackmcdade** [comment]
I apologize. Caching. It's working :) Thanks!

**Comment by euvl** [comment]
@jackmcdade Hey, just wanted to say that I had to rename component to `vue-js-popover` due to number of ppl complaining that the package name is misleading.

I would recommend to do this in your project dependencies: 
`"vue-js-poporver": "^1.0.3"`

Thanks for using component 😄

**Comment by jackmcdade** [comment]
Ah yeah I guess that does make more sense based on intended usage. I had been planning to use it for a Bootstrap Dropdown replacement.
